"""
parameter_identification.py

Estimate 3R2C building parameters from exact environment-transition data.

Required files
--------------
1. parameter_config.py
2. parameter_identification_model.py
3. results/identification/identification_data.csv

Parameter order
---------------
    [C_env, C_air, R_rc, R_oe, R_er]

Identification procedure
------------------------
1. Load the transition dataset generated by the updated
   collect_identification_data.py.

2. Verify that the exact identification model reproduces the dataset
   when the true parameters are used.

3. Evaluate the generic parameter values.

4. Start bounded nonlinear least-squares optimization from the generic
   parameter values.

5. Evaluate and save results for:
   - generic parameters
   - identified parameters
   - true parameters

Important
---------
The identification model now exactly reconstructs:

- the continuous 3R2C matrices;
- the 300-second zero-order-hold discretization;
- the six internal PI-controller loops;
- airflow and supply-air heat transfer;
- terminal reheat;
- the 30% / 70% solar-gain split.

No reconstructed Q_HVAC_total_est_W input is used.

TRUE_PARAMS are used only for model-reproduction checks and final
accuracy evaluation. They are not supplied to the optimizer.
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path
from typing import Dict, List, Mapping, Sequence, Tuple

import numpy as np
import pandas as pd
from scipy.optimize import least_squares

from parameter_config import (
    get_generic_params,
    get_parameter_bounds,
    get_true_params,
)

from parameter_identification_model import (
    PARAMETER_NAMES,
    ThreeRTwoCParameters,
    calculate_controller_state_errors,
    calculate_simulation_metrics,
    compute_residual_vector,
    load_identification_dataset,
    simulate_one_step_predictions,
    simulate_rollout,
)


# ============================================================
# Default configuration
# ============================================================

DEFAULT_DATASET_FILE = (
    Path("results")
    / "identification"
    / "identification_data.csv"
)

DEFAULT_OUTPUT_DIRECTORY = (
    Path("results")
    / "identification"
    / "optimization"
)

# The optimizer should initially use independent one-step residuals.
# This is usually more stable and much faster than optimizing a full
# sequential rollout.
DEFAULT_PREDICTION_MODE = "one_step"

DEFAULT_ENVELOPE_WEIGHT = 1.0
DEFAULT_ZONE_WEIGHT = 1.0

DEFAULT_MAX_FUNCTION_EVALUATIONS = 500

DEFAULT_FTOL = 1.0e-10
DEFAULT_XTOL = 1.0e-10
DEFAULT_GTOL = 1.0e-10

# Capacitances and resistances differ greatly in numerical magnitude.
DEFAULT_X_SCALE = "jac"

# Ordinary nonlinear least squares.
DEFAULT_LOSS = "linear"

DEFAULT_VERBOSE = 2

# The exact model should reproduce true-parameter transitions to within
# float32 storage and numerical roundoff.
DEFAULT_TRUE_MODEL_RMSE_TOLERANCE = 1.0e-4

# Require the controller-state reconstruction to agree as well.
DEFAULT_CONTROLLER_STATE_TOLERANCE = 1.0e-6


# ============================================================
# Parameter conversion helpers
# ============================================================

def dictionary_to_parameter_array(
    parameters: Mapping[str, float],
) -> np.ndarray:
    """
    Convert a parameter dictionary to the standard array order.

    Order:
        [C_env, C_air, R_rc, R_oe, R_er]
    """

    missing_parameters = [
        parameter_name
        for parameter_name in PARAMETER_NAMES
        if parameter_name not in parameters
    ]

    if missing_parameters:
        raise KeyError(
            "Missing parameters: "
            + ", ".join(missing_parameters)
        )

    parameter_values = np.array(
        [
            float(parameters[parameter_name])
            for parameter_name in PARAMETER_NAMES
        ],
        dtype=np.float64,
    )

    if not np.all(np.isfinite(parameter_values)):
        raise ValueError(
            "All parameter values must be finite."
        )

    if np.any(parameter_values <= 0.0):
        raise ValueError(
            "All parameter values must be positive."
        )

    return parameter_values


def parameter_array_to_dictionary(
    parameter_values: Sequence[float],
) -> Dict[str, float]:
    """
    Convert a five-element parameter array to a dictionary.
    """

    parameters = ThreeRTwoCParameters.from_array(
        parameter_values
    )

    return parameters.to_dict()


def bounds_to_arrays(
    bounds: Mapping[str, Tuple[float, float]],
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Convert parameter-bound dictionaries to lower and upper arrays.
    """

    lower_values: List[float] = []
    upper_values: List[float] = []

    for parameter_name in PARAMETER_NAMES:
        if parameter_name not in bounds:
            raise KeyError(
                f"Missing bounds for parameter "
                f"{parameter_name}."
            )

        lower_bound, upper_bound = bounds[
            parameter_name
        ]

        lower_bound = float(lower_bound)
        upper_bound = float(upper_bound)

        if not np.isfinite(lower_bound):
            raise ValueError(
                f"Lower bound for {parameter_name} "
                "must be finite."
            )

        if not np.isfinite(upper_bound):
            raise ValueError(
                f"Upper bound for {parameter_name} "
                "must be finite."
            )

        if lower_bound <= 0.0:
            raise ValueError(
                f"Lower bound for {parameter_name} "
                "must be positive."
            )

        if lower_bound >= upper_bound:
            raise ValueError(
                f"Lower bound must be smaller than the "
                f"upper bound for {parameter_name}."
            )

        lower_values.append(lower_bound)
        upper_values.append(upper_bound)

    return (
        np.asarray(
            lower_values,
            dtype=np.float64,
        ),
        np.asarray(
            upper_values,
            dtype=np.float64,
        ),
    )


def verify_initial_guess_inside_bounds(
    initial_guess: np.ndarray,
    lower_bounds: np.ndarray,
    upper_bounds: np.ndarray,
) -> None:
    """
    Ensure that the generic initial guess lies inside all bounds.
    """

    below_lower_bound = (
        initial_guess < lower_bounds
    )

    above_upper_bound = (
        initial_guess > upper_bounds
    )

    if (
        np.any(below_lower_bound)
        or np.any(above_upper_bound)
    ):
        invalid_parameter_names = [
            PARAMETER_NAMES[index]
            for index in range(
                len(PARAMETER_NAMES)
            )
            if (
                below_lower_bound[index]
                or above_upper_bound[index]
            )
        ]

        raise ValueError(
            "Initial generic parameters are outside "
            "the configured bounds for: "
            + ", ".join(
                invalid_parameter_names
            )
        )


# ============================================================
# Objective wrapper
# ============================================================

class IdentificationObjective:
    """
    Callable least-squares objective with evaluation tracking.

    SciPy's least_squares does not expose an iteration callback in all
    supported SciPy versions. Therefore, this class records every
    objective-function call.

    The resulting CSV is an objective-evaluation history, not a strict
    optimizer-iteration history.
    """

    def __init__(
        self,
        dataset: pd.DataFrame,
        prediction_mode: str,
        envelope_weight: float,
        zone_weight: float,
        print_every: int = 10,
    ) -> None:
        self.dataset = dataset
        self.prediction_mode = (
            prediction_mode
        )

        self.envelope_weight = float(
            envelope_weight
        )

        self.zone_weight = float(
            zone_weight
        )

        self.print_every = int(
            print_every
        )

        self.evaluation_count = 0

        self.history: List[
            Dict[str, float]
        ] = []

        self.best_mse = np.inf

        self.best_parameters: (
            np.ndarray | None
        ) = None

    def __call__(
        self,
        parameter_values: np.ndarray,
    ) -> np.ndarray:
        """
        Evaluate the weighted temperature residual vector.
        """

        self.evaluation_count += 1

        try:
            residuals = compute_residual_vector(
                parameters=parameter_values,
                dataset=self.dataset,
                envelope_weight=(
                    self.envelope_weight
                ),
                zone_weight=(
                    self.zone_weight
                ),
                simulation_mode=(
                    self.prediction_mode
                ),
                normalize_by_samples=False,
            )

        except Exception as error:
            print(
                f"[ERROR] Objective evaluation "
                f"{self.evaluation_count} failed."
            )

            print(
                "Parameter values:"
            )

            for parameter_name, value in zip(
                PARAMETER_NAMES,
                parameter_values,
            ):
                print(
                    f"  {parameter_name}: "
                    f"{float(value):.12g}"
                )

            raise RuntimeError(
                "Parameter-identification objective "
                "evaluation failed."
            ) from error

        mean_squared_error = float(
            np.mean(
                residuals ** 2
            )
        )

        root_mean_squared_error = float(
            np.sqrt(
                mean_squared_error
            )
        )

        least_squares_cost = float(
            0.5
            * np.sum(
                residuals ** 2
            )
        )

        if mean_squared_error < self.best_mse:
            self.best_mse = (
                mean_squared_error
            )

            self.best_parameters = (
                np.asarray(
                    parameter_values,
                    dtype=np.float64,
                ).copy()
            )

        history_row: Dict[str, float] = {
            "evaluation": float(
                self.evaluation_count
            ),
            "weighted_mse":
                mean_squared_error,
            "weighted_rmse":
                root_mean_squared_error,
            "least_squares_cost":
                least_squares_cost,
            "best_weighted_mse_so_far":
                float(self.best_mse),
            "best_weighted_rmse_so_far":
                float(
                    np.sqrt(
                        self.best_mse
                    )
                ),
        }

        for parameter_index, parameter_name in enumerate(
            PARAMETER_NAMES
        ):
            history_row[
                parameter_name
            ] = float(
                parameter_values[
                    parameter_index
                ]
            )

        self.history.append(
            history_row
        )

        should_print = (
            self.print_every > 0
            and (
                self.evaluation_count == 1
                or self.evaluation_count
                % self.print_every
                == 0
            )
        )

        if should_print:
            print(
                f"Objective evaluation "
                f"{self.evaluation_count:4d} | "
                f"weighted RMSE = "
                f"{root_mean_squared_error:.12g} °C | "
                f"best = "
                f"{np.sqrt(self.best_mse):.12g} °C"
            )

        return residuals


# ============================================================
# Parameter-set evaluation
# ============================================================

def evaluate_parameter_set(
    parameter_values: Sequence[float],
    dataset: pd.DataFrame,
) -> Dict[str, object]:
    """
    Evaluate a parameter set in one-step and rollout modes.
    """

    parameters = (
        ThreeRTwoCParameters
        .from_array(
            parameter_values
        )
    )

    one_step_predictions = (
        simulate_one_step_predictions(
            parameters=parameters,
            dataset=dataset,
        )
    )

    rollout_predictions = (
        simulate_rollout(
            parameters=parameters,
            dataset=dataset,
        )
    )

    one_step_metrics = (
        calculate_simulation_metrics(
            one_step_predictions
        )
    )

    rollout_metrics = (
        calculate_simulation_metrics(
            rollout_predictions
        )
    )

    return {
        "parameters":
            parameters.to_dict(),
        "one_step_predictions":
            one_step_predictions,
        "rollout_predictions":
            rollout_predictions,
        "one_step_metrics":
            one_step_metrics,
        "rollout_metrics":
            rollout_metrics,
    }


# ============================================================
# Exact-model reproduction checks
# ============================================================

def maximum_finite_absolute_value(
    values: pd.Series,
) -> float:
    """
    Return the maximum absolute finite value in a Series.
    """

    numeric_values = pd.to_numeric(
        values,
        errors="coerce",
    ).to_numpy(
        dtype=np.float64
    )

    finite_values = numeric_values[
        np.isfinite(
            numeric_values
        )
    ]

    if finite_values.size == 0:
        return np.nan

    return float(
        np.max(
            np.abs(
                finite_values
            )
        )
    )


def run_true_parameter_reproduction_check(
    true_parameter_values: Sequence[float],
    dataset: pd.DataFrame,
    rmse_tolerance: float,
    controller_tolerance: float,
    output_directory: Path,
    allow_failed_check: bool,
) -> Dict[str, object]:
    """
    Confirm that the identification model reproduces the environment.

    Optimization should not begin unless the true parameters reproduce
    both temperature states to approximately numerical precision.
    """

    true_evaluation = (
        evaluate_parameter_set(
            parameter_values=(
                true_parameter_values
            ),
            dataset=dataset,
        )
    )

    one_step_predictions = (
        true_evaluation[
            "one_step_predictions"
        ]
    )

    one_step_metrics = (
        true_evaluation[
            "one_step_metrics"
        ]
    )

    rollout_metrics = (
        true_evaluation[
            "rollout_metrics"
        ]
    )

    controller_diagnostics = (
        calculate_controller_state_errors(
            predictions=(
                one_step_predictions
            ),
            dataset=dataset,
        )
    )

    controller_error_columns = [
        column_name
        for column_name in (
            "integral_error_end_error",
            "prev_zat_sp_end_error",
            "damper_signal_end_error",
            "m_fan_end_error",
        )
        if column_name
        in controller_diagnostics.columns
    ]

    maximum_controller_errors = {}

    for column_name in controller_error_columns:
        maximum_controller_errors[
            column_name
        ] = (
            maximum_finite_absolute_value(
                controller_diagnostics[
                    column_name
                ]
            )
        )

    finite_controller_errors = [
        value
        for value in (
            maximum_controller_errors
            .values()
        )
        if np.isfinite(value)
    ]

    maximum_controller_error = (
        max(finite_controller_errors)
        if finite_controller_errors
        else np.nan
    )

    temperature_check_passed = (
        one_step_metrics.combined_rmse
        <= rmse_tolerance
    )

    controller_check_passed = (
        not finite_controller_errors
        or maximum_controller_error
        <= controller_tolerance
    )

    full_check_passed = (
        temperature_check_passed
        and controller_check_passed
    )

    reproduction_directory = (
        output_directory
        / "true_parameter_reproduction"
    )

    reproduction_directory.mkdir(
        parents=True,
        exist_ok=True,
    )

    controller_diagnostics.to_csv(
        reproduction_directory
        / "true_parameters_one_step_diagnostics.csv",
        index=False,
    )

    true_evaluation[
        "rollout_predictions"
    ].to_csv(
        reproduction_directory
        / "true_parameters_rollout_diagnostics.csv",
        index=False,
    )

    reproduction_summary = pd.DataFrame(
        [
            {
                "one_step_envelope_rmse":
                    one_step_metrics
                    .envelope_rmse,
                "one_step_zone_rmse":
                    one_step_metrics
                    .zone_rmse,
                "one_step_combined_rmse":
                    one_step_metrics
                    .combined_rmse,
                "rollout_envelope_rmse":
                    rollout_metrics
                    .envelope_rmse,
                "rollout_zone_rmse":
                    rollout_metrics
                    .zone_rmse,
                "rollout_combined_rmse":
                    rollout_metrics
                    .combined_rmse,
                "temperature_rmse_tolerance":
                    float(
                        rmse_tolerance
                    ),
                "controller_tolerance":
                    float(
                        controller_tolerance
                    ),
                "maximum_controller_error":
                    float(
                        maximum_controller_error
                    )
                    if np.isfinite(
                        maximum_controller_error
                    )
                    else np.nan,
                "temperature_check_passed":
                    bool(
                        temperature_check_passed
                    ),
                "controller_check_passed":
                    bool(
                        controller_check_passed
                    ),
                "full_check_passed":
                    bool(
                        full_check_passed
                    ),
            }
        ]
    )

    reproduction_summary.to_csv(
        reproduction_directory
        / "true_parameter_reproduction_summary.csv",
        index=False,
    )

    print("=" * 78)
    print("TRUE-PARAMETER MODEL-REPRODUCTION CHECK")
    print("=" * 78)

    print(
        f"One-step envelope RMSE: "
        f"{one_step_metrics.envelope_rmse:.12g} °C"
    )

    print(
        f"One-step zone RMSE:     "
        f"{one_step_metrics.zone_rmse:.12g} °C"
    )

    print(
        f"One-step combined RMSE: "
        f"{one_step_metrics.combined_rmse:.12g} °C"
    )

    print()

    print(
        f"Rollout envelope RMSE:  "
        f"{rollout_metrics.envelope_rmse:.12g} °C"
    )

    print(
        f"Rollout zone RMSE:      "
        f"{rollout_metrics.zone_rmse:.12g} °C"
    )

    print(
        f"Rollout combined RMSE:  "
        f"{rollout_metrics.combined_rmse:.12g} °C"
    )

    if finite_controller_errors:
        print()

        print(
            "Maximum controller-state errors:"
        )

        for (
            column_name,
            maximum_error,
        ) in maximum_controller_errors.items():
            print(
                f"  {column_name:<32} "
                f"{maximum_error:.12g}"
            )

    print()

    if full_check_passed:
        print(
            "PASS: The exact identification model "
            "reproduces the true environment."
        )

    else:
        print(
            "FAIL: The true parameters do not reproduce "
            "the collected transitions within tolerance."
        )

        print(
            "Do not trust parameter-optimization results "
            "until this mismatch is resolved."
        )

    print("=" * 78)
    print()

    if (
        not full_check_passed
        and not allow_failed_check
    ):
        raise RuntimeError(
            "True-parameter reproduction check failed. "
            "Optimization was stopped. Inspect:\n"
            f"{reproduction_directory}"
        )

    return {
        "evaluation":
            true_evaluation,
        "controller_diagnostics":
            controller_diagnostics,
        "summary":
            reproduction_summary,
        "temperature_check_passed":
            temperature_check_passed,
        "controller_check_passed":
            controller_check_passed,
        "full_check_passed":
            full_check_passed,
    }


# ============================================================
# Reporting helpers
# ============================================================

def relative_error_percent(
    estimate: float,
    reference: float,
) -> float:
    """
    Return absolute relative error as a percentage.
    """

    estimate = float(estimate)
    reference = float(reference)

    if reference == 0.0:
        return np.nan

    return (
        abs(
            estimate
            - reference
        )
        / abs(reference)
        * 100.0
    )


def print_parameter_values(
    title: str,
    parameters: Mapping[str, float],
) -> None:
    """
    Print one parameter set.
    """

    print(title)
    print("-" * 78)

    for parameter_name in PARAMETER_NAMES:
        print(
            f"{parameter_name:<8} = "
            f"{float(parameters[parameter_name]):.12g}"
        )

    print()


def print_metrics(
    title: str,
    evaluation: Dict[str, object],
) -> None:
    """
    Print one-step and rollout metrics.
    """

    one_step_metrics = evaluation[
        "one_step_metrics"
    ]

    rollout_metrics = evaluation[
        "rollout_metrics"
    ]

    print(title)
    print("-" * 78)

    print(
        f"One-step envelope RMSE: "
        f"{one_step_metrics.envelope_rmse:.12g} °C"
    )

    print(
        f"One-step zone RMSE:     "
        f"{one_step_metrics.zone_rmse:.12g} °C"
    )

    print(
        f"One-step combined RMSE: "
        f"{one_step_metrics.combined_rmse:.12g} °C"
    )

    print()

    print(
        f"Rollout envelope RMSE:  "
        f"{rollout_metrics.envelope_rmse:.12g} °C"
    )

    print(
        f"Rollout zone RMSE:      "
        f"{rollout_metrics.zone_rmse:.12g} °C"
    )

    print(
        f"Rollout combined RMSE:  "
        f"{rollout_metrics.combined_rmse:.12g} °C"
    )

    print()


def build_parameter_comparison_table(
    true_parameters: Mapping[str, float],
    generic_parameters: Mapping[str, float],
    identified_parameters: Mapping[str, float],
    parameter_bounds: Mapping[
        str,
        Tuple[float, float],
    ],
) -> pd.DataFrame:
    """
    Build the true/generic/identified parameter comparison table.
    """

    rows = []

    for parameter_name in PARAMETER_NAMES:
        true_value = float(
            true_parameters[
                parameter_name
            ]
        )

        generic_value = float(
            generic_parameters[
                parameter_name
            ]
        )

        identified_value = float(
            identified_parameters[
                parameter_name
            ]
        )

        lower_bound, upper_bound = (
            parameter_bounds[
                parameter_name
            ]
        )

        generic_relative_error = (
            relative_error_percent(
                estimate=generic_value,
                reference=true_value,
            )
        )

        identified_relative_error = (
            relative_error_percent(
                estimate=identified_value,
                reference=true_value,
            )
        )

        rows.append(
            {
                "parameter":
                    parameter_name,
                "true_value":
                    true_value,
                "generic_value":
                    generic_value,
                "identified_value":
                    identified_value,
                "lower_bound":
                    float(lower_bound),
                "upper_bound":
                    float(upper_bound),
                "generic_relative_error_percent":
                    generic_relative_error,
                "identified_relative_error_percent":
                    identified_relative_error,
                "error_improvement_percent_points":
                    (
                        generic_relative_error
                        - identified_relative_error
                    ),
                "identified_at_lower_bound":
                    bool(
                        np.isclose(
                            identified_value,
                            lower_bound,
                            rtol=1.0e-5,
                            atol=1.0e-12,
                        )
                    ),
                "identified_at_upper_bound":
                    bool(
                        np.isclose(
                            identified_value,
                            upper_bound,
                            rtol=1.0e-5,
                            atol=1.0e-12,
                        )
                    ),
            }
        )

    return pd.DataFrame(
        rows
    )


def build_metrics_table(
    generic_evaluation: Dict[str, object],
    identified_evaluation: Dict[str, object],
    true_evaluation: Dict[str, object],
) -> pd.DataFrame:
    """
    Build generic, identified, and true-model metrics.
    """

    rows = []

    evaluations = {
        "generic":
            generic_evaluation,
        "identified":
            identified_evaluation,
        "true":
            true_evaluation,
    }

    for (
        parameter_source,
        evaluation,
    ) in evaluations.items():
        for prediction_mode in (
            "one_step",
            "rollout",
        ):
            metrics = evaluation[
                f"{prediction_mode}_metrics"
            ]

            rows.append(
                {
                    "parameter_source":
                        parameter_source,
                    "prediction_mode":
                        prediction_mode,
                    **metrics.to_dict(),
                }
            )

    return pd.DataFrame(
        rows
    )


def save_parameter_json(
    output_file: Path,
    parameters: Mapping[str, float],
) -> None:
    """
    Save identified parameters in JSON format.
    """

    output_file.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    serializable_parameters = {
        parameter_name: float(
            parameters[
                parameter_name
            ]
        )
        for parameter_name in PARAMETER_NAMES
    }

    with output_file.open(
        "w",
        encoding="utf-8",
    ) as output_stream:
        json.dump(
            serializable_parameters,
            output_stream,
            indent=4,
        )


# ============================================================
# Main identification procedure
# ============================================================

def identify_parameters(
    dataset_file: Path = DEFAULT_DATASET_FILE,
    output_directory: Path = DEFAULT_OUTPUT_DIRECTORY,
    prediction_mode: str = DEFAULT_PREDICTION_MODE,
    envelope_weight: float = DEFAULT_ENVELOPE_WEIGHT,
    zone_weight: float = DEFAULT_ZONE_WEIGHT,
    max_nfev: int = DEFAULT_MAX_FUNCTION_EVALUATIONS,
    ftol: float = DEFAULT_FTOL,
    xtol: float = DEFAULT_XTOL,
    gtol: float = DEFAULT_GTOL,
    loss: str = DEFAULT_LOSS,
    verbose: int = DEFAULT_VERBOSE,
    print_every: int = 10,
    true_model_rmse_tolerance: float = (
        DEFAULT_TRUE_MODEL_RMSE_TOLERANCE
    ),
    controller_state_tolerance: float = (
        DEFAULT_CONTROLLER_STATE_TOLERANCE
    ),
    allow_failed_true_model_check: bool = False,
) -> Dict[str, object]:
    """
    Estimate the five 3R2C parameters.
    """

    dataset_file = Path(
        dataset_file
    )

    output_directory = Path(
        output_directory
    )

    prediction_mode = (
        prediction_mode
        .strip()
        .lower()
        .replace("-", "_")
    )

    if prediction_mode not in {
        "one_step",
        "rollout",
    }:
        raise ValueError(
            "prediction_mode must be either "
            "'one_step' or 'rollout'."
        )

    envelope_weight = float(
        envelope_weight
    )

    zone_weight = float(
        zone_weight
    )

    if (
        not np.isfinite(
            envelope_weight
        )
        or envelope_weight <= 0.0
    ):
        raise ValueError(
            "envelope_weight must be positive "
            "and finite."
        )

    if (
        not np.isfinite(
            zone_weight
        )
        or zone_weight <= 0.0
    ):
        raise ValueError(
            "zone_weight must be positive "
            "and finite."
        )

    if max_nfev < 1:
        raise ValueError(
            "max_nfev must be positive."
        )

    if (
        true_model_rmse_tolerance <= 0.0
        or not np.isfinite(
            true_model_rmse_tolerance
        )
    ):
        raise ValueError(
            "true_model_rmse_tolerance must be "
            "positive and finite."
        )

    if (
        controller_state_tolerance <= 0.0
        or not np.isfinite(
            controller_state_tolerance
        )
    ):
        raise ValueError(
            "controller_state_tolerance must be "
            "positive and finite."
        )

    # --------------------------------------------------------
    # Load dataset and configuration
    # --------------------------------------------------------

    dataset = (
        load_identification_dataset(
            dataset_file
        )
    )

    generic_parameters = (
        get_generic_params()
    )

    true_parameters = (
        get_true_params()
    )

    parameter_bounds = (
        get_parameter_bounds()
    )

    initial_guess = (
        dictionary_to_parameter_array(
            generic_parameters
        )
    )

    true_parameter_array = (
        dictionary_to_parameter_array(
            true_parameters
        )
    )

    (
        lower_bounds,
        upper_bounds,
    ) = bounds_to_arrays(
        parameter_bounds
    )

    verify_initial_guess_inside_bounds(
        initial_guess=initial_guess,
        lower_bounds=lower_bounds,
        upper_bounds=upper_bounds,
    )

    output_directory.mkdir(
        parents=True,
        exist_ok=True,
    )

    print("=" * 78)
    print("3R2C PARAMETER IDENTIFICATION")
    print("=" * 78)

    print(
        f"Dataset:              "
        f"{dataset_file}"
    )

    print(
        f"Number of rows:       "
        f"{len(dataset)}"
    )

    print(
        f"Optimization mode:    "
        f"{prediction_mode}"
    )

    print(
        f"Envelope weight:      "
        f"{envelope_weight}"
    )

    print(
        f"Zone weight:          "
        f"{zone_weight}"
    )

    print(
        "Transition model:     "
        "exact 300-second ZOH + internal PI loops"
    )

    print(
        f"Loss function:        "
        f"{loss}"
    )

    print(
        f"Maximum evaluations:  "
        f"{max_nfev}"
    )

    print(
        "True-model tolerance: "
        f"{true_model_rmse_tolerance:.12g} °C"
    )

    print("=" * 78)
    print()

    print_parameter_values(
        title="Initial generic parameters",
        parameters=generic_parameters,
    )

    print_parameter_values(
        title="True simulation parameters",
        parameters=true_parameters,
    )

    # --------------------------------------------------------
    # Verify exact true-parameter reproduction
    # --------------------------------------------------------

    reproduction_check = (
        run_true_parameter_reproduction_check(
            true_parameter_values=(
                true_parameter_array
            ),
            dataset=dataset,
            rmse_tolerance=(
                true_model_rmse_tolerance
            ),
            controller_tolerance=(
                controller_state_tolerance
            ),
            output_directory=(
                output_directory
            ),
            allow_failed_check=(
                allow_failed_true_model_check
            ),
        )
    )

    true_evaluation = (
        reproduction_check[
            "evaluation"
        ]
    )

    # --------------------------------------------------------
    # Evaluate the generic model
    # --------------------------------------------------------

    print(
        "Evaluating generic parameters..."
    )

    generic_evaluation = (
        evaluate_parameter_set(
            parameter_values=(
                initial_guess
            ),
            dataset=dataset,
        )
    )

    print_metrics(
        title=(
            "Generic-parameter prediction accuracy"
        ),
        evaluation=(
            generic_evaluation
        ),
    )

    # --------------------------------------------------------
    # Construct the optimization objective
    # --------------------------------------------------------

    objective = (
        IdentificationObjective(
            dataset=dataset,
            prediction_mode=(
                prediction_mode
            ),
            envelope_weight=(
                envelope_weight
            ),
            zone_weight=(
                zone_weight
            ),
            print_every=(
                print_every
            ),
        )
    )

    initial_residuals = (
        compute_residual_vector(
            parameters=initial_guess,
            dataset=dataset,
            envelope_weight=(
                envelope_weight
            ),
            zone_weight=(
                zone_weight
            ),
            simulation_mode=(
                prediction_mode
            ),
            normalize_by_samples=False,
        )
    )

    initial_weighted_mse = float(
        np.mean(
            initial_residuals ** 2
        )
    )

    initial_weighted_rmse = float(
        np.sqrt(
            initial_weighted_mse
        )
    )

    # --------------------------------------------------------
    # Run bounded nonlinear least squares
    # --------------------------------------------------------

    print("=" * 78)
    print(
        "STARTING BOUNDED NONLINEAR "
        "LEAST-SQUARES OPTIMIZATION"
    )
    print("=" * 78)

    optimization_start_time = (
        time.perf_counter()
    )

    optimization_result = (
        least_squares(
            fun=objective,
            x0=initial_guess,
            bounds=(
                lower_bounds,
                upper_bounds,
            ),
            method="trf",
            jac="2-point",
            x_scale=DEFAULT_X_SCALE,
            loss=loss,
            ftol=ftol,
            xtol=xtol,
            gtol=gtol,
            max_nfev=max_nfev,
            verbose=verbose,
        )
    )

    elapsed_seconds = (
        time.perf_counter()
        - optimization_start_time
    )

    identified_parameter_array = (
        np.asarray(
            optimization_result.x,
            dtype=np.float64,
        )
    )

    identified_parameters = (
        parameter_array_to_dictionary(
            identified_parameter_array
        )
    )

    final_residuals = (
        compute_residual_vector(
            parameters=(
                identified_parameter_array
            ),
            dataset=dataset,
            envelope_weight=(
                envelope_weight
            ),
            zone_weight=(
                zone_weight
            ),
            simulation_mode=(
                prediction_mode
            ),
            normalize_by_samples=False,
        )
    )

    final_weighted_mse = float(
        np.mean(
            final_residuals ** 2
        )
    )

    final_weighted_rmse = float(
        np.sqrt(
            final_weighted_mse
        )
    )

    # --------------------------------------------------------
    # Evaluate identified parameters
    # --------------------------------------------------------

    print()
    print(
        "Evaluating identified parameters..."
    )

    identified_evaluation = (
        evaluate_parameter_set(
            parameter_values=(
                identified_parameter_array
            ),
            dataset=dataset,
        )
    )

    # --------------------------------------------------------
    # Print optimization results
    # --------------------------------------------------------

    print()
    print("=" * 78)
    print("OPTIMIZATION FINISHED")
    print("=" * 78)

    print(
        f"Success:              "
        f"{optimization_result.success}"
    )

    print(
        f"Status code:          "
        f"{optimization_result.status}"
    )

    print(
        f"Message:              "
        f"{optimization_result.message}"
    )

    print(
        f"Function evaluations: "
        f"{optimization_result.nfev}"
    )

    print(
        f"Jacobian evaluations: "
        f"{optimization_result.njev}"
    )

    print(
        f"Objective calls:      "
        f"{objective.evaluation_count}"
    )

    print(
        f"Final cost:           "
        f"{optimization_result.cost:.12g}"
    )

    print(
        f"Optimality:           "
        f"{optimization_result.optimality:.12g}"
    )

    print(
        f"Elapsed time:         "
        f"{elapsed_seconds:.4f} seconds"
    )

    print(
        f"Initial weighted RMSE: "
        f"{initial_weighted_rmse:.12g} °C"
    )

    print(
        f"Final weighted RMSE:   "
        f"{final_weighted_rmse:.12g} °C"
    )

    print("=" * 78)
    print()

    print_parameter_values(
        title="Identified parameters",
        parameters=(
            identified_parameters
        ),
    )

    print_metrics(
        title=(
            "Identified-parameter prediction accuracy"
        ),
        evaluation=(
            identified_evaluation
        ),
    )

    print_metrics(
        title=(
            "True-parameter prediction accuracy"
        ),
        evaluation=(
            true_evaluation
        ),
    )

    parameter_comparison = (
        build_parameter_comparison_table(
            true_parameters=(
                true_parameters
            ),
            generic_parameters=(
                generic_parameters
            ),
            identified_parameters=(
                identified_parameters
            ),
            parameter_bounds=(
                parameter_bounds
            ),
        )
    )

    print("Parameter comparison")
    print("-" * 78)

    print(
        parameter_comparison[
            [
                "parameter",
                "true_value",
                "generic_value",
                "identified_value",
                "generic_relative_error_percent",
                "identified_relative_error_percent",
            ]
        ].to_string(
            index=False
        )
    )

    print()

    # --------------------------------------------------------
    # Save results
    # --------------------------------------------------------

    identified_json_file = (
        output_directory
        / "identified_parameters.json"
    )

    parameter_csv_file = (
        output_directory
        / "estimated_parameters.csv"
    )

    metrics_csv_file = (
        output_directory
        / "model_metrics.csv"
    )

    summary_csv_file = (
        output_directory
        / "optimization_summary.csv"
    )

    history_csv_file = (
        output_directory
        / "optimization_history.csv"
    )

    generic_one_step_file = (
        output_directory
        / "generic_one_step_predictions.csv"
    )

    generic_rollout_file = (
        output_directory
        / "generic_rollout_predictions.csv"
    )

    identified_one_step_file = (
        output_directory
        / "identified_one_step_predictions.csv"
    )

    identified_rollout_file = (
        output_directory
        / "identified_rollout_predictions.csv"
    )

    true_one_step_file = (
        output_directory
        / "true_one_step_predictions.csv"
    )

    true_rollout_file = (
        output_directory
        / "true_rollout_predictions.csv"
    )

    save_parameter_json(
        output_file=(
            identified_json_file
        ),
        parameters=(
            identified_parameters
        ),
    )

    parameter_comparison.to_csv(
        parameter_csv_file,
        index=False,
    )

    metrics_table = (
        build_metrics_table(
            generic_evaluation=(
                generic_evaluation
            ),
            identified_evaluation=(
                identified_evaluation
            ),
            true_evaluation=(
                true_evaluation
            ),
        )
    )

    metrics_table.to_csv(
        metrics_csv_file,
        index=False,
    )

    jacobian_evaluations = (
        int(
            optimization_result.njev
        )
        if optimization_result.njev
        is not None
        else np.nan
    )

    optimization_summary = (
        pd.DataFrame(
            [
                {
                    "dataset_file":
                        str(dataset_file),
                    "number_of_rows":
                        int(len(dataset)),
                    "prediction_mode":
                        prediction_mode,
                    "transition_model":
                        (
                            "exact_300_second_zoh_"
                            "with_internal_pi_loops"
                        ),
                    "envelope_weight":
                        float(
                            envelope_weight
                        ),
                    "zone_weight":
                        float(
                            zone_weight
                        ),
                    "loss_function":
                        loss,
                    "true_model_check_passed":
                        bool(
                            reproduction_check[
                                "full_check_passed"
                            ]
                        ),
                    "true_model_rmse_tolerance":
                        float(
                            true_model_rmse_tolerance
                        ),
                    "success":
                        bool(
                            optimization_result
                            .success
                        ),
                    "status":
                        int(
                            optimization_result
                            .status
                        ),
                    "message":
                        str(
                            optimization_result
                            .message
                        ),
                    "function_evaluations":
                        int(
                            optimization_result
                            .nfev
                        ),
                    "jacobian_evaluations":
                        jacobian_evaluations,
                    "objective_calls_recorded":
                        int(
                            objective
                            .evaluation_count
                        ),
                    "initial_weighted_mse":
                        initial_weighted_mse,
                    "initial_weighted_rmse":
                        initial_weighted_rmse,
                    "final_weighted_mse":
                        final_weighted_mse,
                    "final_weighted_rmse":
                        final_weighted_rmse,
                    "least_squares_cost":
                        float(
                            optimization_result
                            .cost
                        ),
                    "optimality":
                        float(
                            optimization_result
                            .optimality
                        ),
                    "active_mask":
                        json.dumps(
                            optimization_result
                            .active_mask
                            .tolist()
                        ),
                    "elapsed_seconds":
                        float(
                            elapsed_seconds
                        ),
                    "ftol":
                        float(ftol),
                    "xtol":
                        float(xtol),
                    "gtol":
                        float(gtol),
                    "max_nfev":
                        int(max_nfev),
                }
            ]
        )
    )

    optimization_summary.to_csv(
        summary_csv_file,
        index=False,
    )

    history_table = pd.DataFrame(
        objective.history
    )

    history_table.to_csv(
        history_csv_file,
        index=False,
    )

    generic_evaluation[
        "one_step_predictions"
    ].to_csv(
        generic_one_step_file,
        index=False,
    )

    generic_evaluation[
        "rollout_predictions"
    ].to_csv(
        generic_rollout_file,
        index=False,
    )

    identified_evaluation[
        "one_step_predictions"
    ].to_csv(
        identified_one_step_file,
        index=False,
    )

    identified_evaluation[
        "rollout_predictions"
    ].to_csv(
        identified_rollout_file,
        index=False,
    )

    true_evaluation[
        "one_step_predictions"
    ].to_csv(
        true_one_step_file,
        index=False,
    )

    true_evaluation[
        "rollout_predictions"
    ].to_csv(
        true_rollout_file,
        index=False,
    )

    print("=" * 78)
    print("SAVED OUTPUT FILES")
    print("=" * 78)

    print(
        f"Identified parameters: "
        f"{identified_json_file}"
    )

    print(
        f"Parameter comparison:  "
        f"{parameter_csv_file}"
    )

    print(
        f"Model metrics:         "
        f"{metrics_csv_file}"
    )

    print(
        f"Optimization summary:  "
        f"{summary_csv_file}"
    )

    print(
        f"Evaluation history:    "
        f"{history_csv_file}"
    )

    print(
        "True-model diagnostics: "
        f"{output_directory / 'true_parameter_reproduction'}"
    )

    print("=" * 78)

    return {
        "optimization_result":
            optimization_result,
        "identified_parameters":
            identified_parameters,
        "generic_evaluation":
            generic_evaluation,
        "identified_evaluation":
            identified_evaluation,
        "true_evaluation":
            true_evaluation,
        "true_parameter_reproduction":
            reproduction_check,
        "parameter_comparison":
            parameter_comparison,
        "metrics_table":
            metrics_table,
        "optimization_summary":
            optimization_summary,
        "history":
            history_table,
    }


# ============================================================
# Command-line interface
# ============================================================

def parse_arguments() -> argparse.Namespace:
    """
    Parse command-line options.
    """

    parser = argparse.ArgumentParser(
        description=(
            "Estimate exact-environment 3R2C building "
            "parameters from transition data."
        )
    )

    parser.add_argument(
        "--dataset",
        type=Path,
        default=DEFAULT_DATASET_FILE,
        help=(
            "Identification transition CSV file."
        ),
    )

    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIRECTORY,
        help=(
            "Directory for optimization outputs."
        ),
    )

    parser.add_argument(
        "--prediction-mode",
        choices=[
            "one_step",
            "rollout",
        ],
        default=DEFAULT_PREDICTION_MODE,
        help=(
            "Residual mode used by the optimizer. "
            "one_step is recommended initially."
        ),
    )

    parser.add_argument(
        "--envelope-weight",
        type=float,
        default=DEFAULT_ENVELOPE_WEIGHT,
        help=(
            "Positive weight for envelope-temperature "
            "residuals."
        ),
    )

    parser.add_argument(
        "--zone-weight",
        type=float,
        default=DEFAULT_ZONE_WEIGHT,
        help=(
            "Positive weight for zone-temperature "
            "residuals."
        ),
    )

    parser.add_argument(
        "--max-nfev",
        type=int,
        default=(
            DEFAULT_MAX_FUNCTION_EVALUATIONS
        ),
        help=(
            "Maximum SciPy objective-function "
            "evaluations."
        ),
    )

    parser.add_argument(
        "--ftol",
        type=float,
        default=DEFAULT_FTOL,
        help=(
            "Cost-function convergence tolerance."
        ),
    )

    parser.add_argument(
        "--xtol",
        type=float,
        default=DEFAULT_XTOL,
        help=(
            "Parameter convergence tolerance."
        ),
    )

    parser.add_argument(
        "--gtol",
        type=float,
        default=DEFAULT_GTOL,
        help=(
            "Gradient convergence tolerance."
        ),
    )

    parser.add_argument(
        "--loss",
        choices=[
            "linear",
            "soft_l1",
            "huber",
            "cauchy",
            "arctan",
        ],
        default=DEFAULT_LOSS,
        help=(
            "Least-squares loss function."
        ),
    )

    parser.add_argument(
        "--verbose",
        type=int,
        choices=[
            0,
            1,
            2,
        ],
        default=DEFAULT_VERBOSE,
        help=(
            "SciPy optimizer verbosity."
        ),
    )

    parser.add_argument(
        "--print-every",
        type=int,
        default=10,
        help=(
            "Print objective RMSE every N calls. "
            "Use 0 to disable."
        ),
    )

    parser.add_argument(
        "--true-model-rmse-tolerance",
        type=float,
        default=(
            DEFAULT_TRUE_MODEL_RMSE_TOLERANCE
        ),
        help=(
            "Maximum allowed true-parameter one-step "
            "combined RMSE before optimization."
        ),
    )

    parser.add_argument(
        "--controller-state-tolerance",
        type=float,
        default=(
            DEFAULT_CONTROLLER_STATE_TOLERANCE
        ),
        help=(
            "Maximum allowed exact-controller-state "
            "reproduction error."
        ),
    )

    parser.add_argument(
        "--allow-failed-true-model-check",
        action="store_true",
        help=(
            "Continue optimization even when the true "
            "parameters fail the exact reproduction check. "
            "This is intended only for debugging."
        ),
    )

    return parser.parse_args()


def main() -> None:
    """
    Program entry point.
    """

    arguments = parse_arguments()

    identify_parameters(
        dataset_file=(
            arguments.dataset
        ),
        output_directory=(
            arguments.output_dir
        ),
        prediction_mode=(
            arguments.prediction_mode
        ),
        envelope_weight=(
            arguments.envelope_weight
        ),
        zone_weight=(
            arguments.zone_weight
        ),
        max_nfev=(
            arguments.max_nfev
        ),
        ftol=arguments.ftol,
        xtol=arguments.xtol,
        gtol=arguments.gtol,
        loss=arguments.loss,
        verbose=arguments.verbose,
        print_every=(
            arguments.print_every
        ),
        true_model_rmse_tolerance=(
            arguments
            .true_model_rmse_tolerance
        ),
        controller_state_tolerance=(
            arguments
            .controller_state_tolerance
        ),
        allow_failed_true_model_check=(
            arguments
            .allow_failed_true_model_check
        ),
    )


if __name__ == "__main__":
    main()